### PR TITLE
Exported things for extensibility (& added linting with prettier)

### PR DESCRIPTION
**Pull request by iPurpl3x**

### CODE REVIEW

**Review by clarkwinkelmann — COMMENTED** [review]
Thanks for the PR!

I don't like those prettier change very much though. The diff is massive and differs quite a lot from my personal formatting (which explains the large diff, since I originally wrote most of this code :sweat_smile: )

Could we maybe split the export part into its own PR? I'd love to get that merged. A discussion with the FoF team should be held if we decide on some more consistent formatting between projects.

**Comment by iPurpl3x** [comment]
@clarkwinkelmann Sure I can do that. I just thought that taking the config from another FoF extension and formatting the code here would be OK, but whatever.

**Comment by luceos** [comment]
@iPurpl3x even though fof extensions all fall under the same group, most of them are often still individually maintained. The intent is that multiple people can maintain them should the need arise (my extensions being a great example).

@clarkwinkelmann I would prefer having team wide conventions, not sure if we could enforce most through the github global team repository? (cc @datitisev)

**Comment by clarkwinkelmann** [comment]
We had a quick chat in the Discord server yesterday and you're right, the prettier config you used is the one we decided to use internally.

However we have not yet used it on any of the extensions originally created by myself, and I only realize now that the formatting doesn't play very nice with my personal preference of not using JSX and instead using `m()` / plain javascript objects for the templates. Prettier adds a ton of whitespace and newlines which defeat the compactness of using `m()` IMO.

I'd need to check whether there's a config for Prettier that allows keeping more things on their own lines as to not lose the compact templates. Or we should convert everything to JSX, but I'm personally not a fan of JSX.

I do think we should have a single prettier config for all our repos. But right now there's also that big difference between extensions that use JSX, those that don't, and those that have a strange hybrid solution. And soon there will probably be even more differences with typescript...

**Comment by clarkwinkelmann** [comment]
I cherry-picked 9bf04bcb887ee3f30c3a569e0e4d06ee7d588949 into the latest release, thanks for the help :+1:

**Pull request closed without merging**
